#
# Dockerfile for CI and Flexpart container images
# Build Examples:
#	- podman build -t harbor.wolke.img.univie.ac.at/flexpart/almalinux8:jasper -f Dockerfile
#
FROM almalinux:8-minimal 
#
# Build development image (with/without jasper)
# jasper was used in FP 10.4 (eccodes, emoslib)
#
RUN microdnf install -y epel-release && \
	microdnf install -y --enablerepo=powertools make netcdf-fortran-devel.x86_64 netcdf.x86_64 cmake tar gcc-c++ perl jasper-libs.x86_64 && \
	microdnf clean all -y

#
# Download ECCODES Version 
# note 2.30.0 has an issue!!!
#
RUN curl https://confluence.ecmwf.int/download/attachments/45757960/eccodes-2.31.0-Source.tar.gz | tar xz
RUN mkdir build && \
	cd build && \
	cmake -DENABLE_ECCODES_OMP_THREADS=ON ../eccodes-*/ && \
	make -j8 && \
	make install
#
# set environment variables
#
ENV FC=gfortran
ENV LIBRARY_PATH=/usr/lib64:/usr/local/lib64
ENV CPATH=/usr/include:/usr/local/include:/usr/lib64/gfortran/modules

WORKDIR /
# clone just that version for FLEXPART v10.4 + small fixes
RUN git clone --branch v10.4.1 --single-branch https://gitlab.phaidra.org/flexpart/flexpart.git \
	&& cp -r flexpart/src /src

ENV COMMIT=v10.4
COPY ./tests/default_options /options

# since the new data set is larger, we download the data for the container
RUN wget  -r --no-parent -A 'EC*' -P /inputs "https://webdata.wolke.img.univie.ac.at/flexpart/"
COPY ./AVAILABLE /inputs/
# Entrypoint script (user tips)
COPY ./entrypoint.sh /entrypoint.sh
WORKDIR /src
#
# compile using a subset of microarch
# need to fix march to x86_64_v3 , remove mtune
# here generic means core_avx2
RUN make -f makefile_gfortran eta=no arch=generic \
	&& make -f makefile_gfortran arch=generic \
	&& mkdir -p /output \
	&& echo -e "/options/\n/output/\n/inputs/\n/inputs/AVAILABLE" > /pathnames
# In the Dockerfile, the ENTRYPOINT command defines the executable, 
# while CMD sets the default parameter. 
# so here our entrypoint run script and default FLEXPART_ETA or FLEXPART
ENTRYPOINT ["/entrypoint.sh"]
# Could be FLEXPART_ETA pathnames_custom
CMD ["FLEXPART"]
